// ======================================
// MadGraph Reader Root Script
// Reads the Root file generated by MadGraph and converted by ExRootAnalysis
// Example for the process p p > mu+ mu-
// EMG 26-07-22
// ======================================

#include "ostream"
#include "stdlib.h"
#include "TFile.h"
#include "TTreeReader.h"
#include "TTreeReaderArray.h"
#include "TLorentzVector.h"
#include "TMath.h"

void Anglereader(){
    TFile *file = new TFile("unweighted_events.root");    
    TTreeReader reader("LHEF", file);
    TTreeReaderArray<long long>    Number(reader, "Event.Number"); // Numero do Evento
    TTreeReaderArray<Int_t>    NParticles(reader, "Particle_size"); // Numero de particulas no evento
    TTreeReaderArray<Int_t>           PID(reader, "Particle.PID");
    TTreeReaderArray<Int_t>        Status(reader, "Particle.Status"); 
    TTreeReaderArray<Double_t>          E(reader, "Particle.E");
    TTreeReaderArray<Double_t>         Px(reader, "Particle.Px");
    TTreeReaderArray<Double_t>         Py(reader, "Particle.Py");
    TTreeReaderArray<Double_t>         Pz(reader, "Particle.Pz");
    TTreeReaderArray<Double_t>         PT(reader, "Particle.PT");
    TTreeReaderArray<Double_t>        Eta(reader, "Particle.Eta");
    TTreeReaderArray<Double_t>        Phi(reader, "Particle.Phi");


    TH1F* hPhi = new TH1F("Phi","Muon Pair Phi Diff" ,80,-4,4);
    TLorentzVector phiMuP;        // Mu+ quadrimomentum 
    TLorentzVector phiMuM;        // Mu- 

    while(reader.Next()){
        for(Int_t i = 0; i < NParticles[0]; i++) {
           if(PID[i] == -13){ phiMuP.SetPtEtaPhiM(PT[i],Eta[i],Phi[i],E[i]); } // Sets Mu+ Phi Angle     
           if(PID[i] ==  13){ phiMuM.SetPtEtaPhiM(PT[i],Eta[i],Phi[i],E[i]); } // Set Mu- Phi Angle      
        }
        hPhi->Fill((phiMuP.Phi() - phiMuM.Phi()));        // Fills the histogram with muon pair Phi Angle
    }

    TCanvas* c = new TCanvas("c"," ",0,0,1600,1200);
    hPhi->Draw();
    c->Print("MuonPair_Phi_Diff.pdf");
    }
