// ======================================
// MadGraph Reader Root Script
// Reads the Root file generated by MadGraph and converted by ExRootAnalysis
// Example for the process p p > mu+ mu-
// EMG 26-07-22
// ======================================

#include "ostream"
#include "stdlib.h"
#include "TFile.h"
#include "TTreeReader.h"
#include "TTreeReaderArray.h"
#include "TLorentzVector.h"

void Energyreader(){
    TFile *file = new TFile("unweighted_events.root");    
    TTreeReader reader("LHEF", file);
    TTreeReaderArray<long long>    Number(reader, "Event.Number"); // Numero do Evento
    TTreeReaderArray<Int_t>    NParticles(reader, "Particle_size"); // Numero de particulas no evento
    TTreeReaderArray<Int_t>           PID(reader, "Particle.PID");
    TTreeReaderArray<Int_t>        Status(reader, "Particle.Status"); 
    TTreeReaderArray<Double_t>          E(reader, "Particle.E");
    TTreeReaderArray<Double_t>         Px(reader, "Particle.Px");
    TTreeReaderArray<Double_t>         Py(reader, "Particle.Py");
    TTreeReaderArray<Double_t>         Pz(reader, "Particle.Pz");
    TTreeReaderArray<Double_t>         PT(reader, "Particle.PT");
    TTreeReaderArray<Double_t>        Eta(reader, "Particle.Eta");
    TTreeReaderArray<Double_t>        Phi(reader, "Particle.Phi");


    TH1F* hInvMass = new TH1F("invMass","Muon Pair Invariant Mass" ,100,0,200);
    TLorentzVector pMuP;        // Mu+ quadrimomentum 
    TLorentzVector pMuM;        // Mu- quadrimomentum

    while(reader.Next()){
        for(Int_t i = 0; i < NParticles[0]; i++) {
           if(PID[i] == -13){ pMuP.SetPxPyPzE(Px[i],Py[i],Pz[i],E[i]); } // Sets Mu+ quadrimomentum      
           if(PID[i] ==  13){ pMuM.SetPxPyPzE(Px[i],Py[i],Pz[i],E[i]); } // Sets Mu- quadrimomentum      
        }
        hInvMass->Fill((pMuP+pMuM).M());        // Fills the histogram with muon pair invariant mass
    }

    TCanvas* c = new TCanvas("c"," ",0,0,1600,1200);
    hInvMass->Draw();
    c->Print("MuonPairInvMass.pdf");
}
